# This is a basic workflow to help you get started with Actions

name: linter-check

# Controls when the workflow will run
on:

  - push:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

 
    steps:
    
      - uses: actions/checkout@v2

      
      - name: install
        run: make install

      - name: run linter
        run: make lint
        
